export const DEFAULT_CITY = "Casablanca";

export const CASABLANCA_NEIGHBORHOODS = [
    "Maârif",
    "Gauthier",
    "Racine",
    "Palmier",
    "Bourgogne",
    "Derb Ghallef",
    "Hôpitaux",
    "Belvédère",
    "Roches Noires",
    "Anfa",
    "Aïn Diab",
    "Californie",
    "L'Oasis",
    "Polo",
    "CIL (Hay El Hanaa)",
    "Sidi Maârouf",
    "Casablanca Finance City (CFC)",
    "Habous (Nouvelle Médina)",
    "Ancienne Médina",
    "Mers Sultan",
    "Derb Sultan",
    "Hay Mohammadi",
    "Al Fida",
    "Aïn Chock",
    "Hay Hassani",
    "Sbata",
    "Ben M'sik",
    "Sidi Othmane",
    "Moulay Rachid",
    "Aïn Sebaâ",
    "Sidi Bernoussi",
    "Sidi Moumen",
    "Lissasfa",
    "Bouskoura (périphérie sud)",
    "Dar Bouazza (périphérie côtière ouest)"
];
